[package]
name = "moodchain"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
primitive-types = "0.12.1"
sha2 = "0.10.6"
actix-web = "4"
serde = {version = "1.0.152", features = ["derive"]}
serde_json = "1.0.91"
